name: Test Extraction

on:
  push:
    branches: [testing]

permissions: 
  contents: read

jobs:
  test_extraciton:
    if: false
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: pip install pytest && pip install -r requirements.txt

    - name: Test with pytest
      working-directory: modular
      run: pytest test_extraction.py